flowchart TD
%% generated in 0.00s
    examples__01_hardcoded_api["examples.01-hardcoded-api<br/>3 funcs"]
    examples__02_inline_config["examples.02-inline-config<br/>1 funcs"]
    examples__03_unused_constants["examples.03-unused-constants<br/>1 funcs"]
    examples__run_all["examples.run_all<br/>3 funcs"]
    src__reko["src.reko<br/>80 funcs"]
